name: decentraland
version: master
summary: Full node for Decentraland Bronze Age
description: |
  Decentraland is an open-source initiative to build a shared virtual reality
   world. In Decentraland, the content of each piece of land is determined by
  its owner. You can become a land owner either by having someone transfer you
  some of their tiles, or by mining new land.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

apps:
  decentraland:
    command: sh -c \"cd $SNAP/lib/node_modules/decentraland && DATA_DIR=$SNAP_USER_DATA/data ./bin/start\"
    plugs: [home, network, network-bind]
  cli:
    command: sh -c \"cd $SNAP/lib/node_modules/decentraland && ./bin/cli\"
    plugs: [home, network]

parts:
  bronzeage-node:
    source: .
    plugin: nodejs
    node-engine: 7.4.0
    build-packages:
      - build-essential
      - python
      - xvfb
      - libgtk2.0-0
      - libxtst-dev
      - libxss-dev
      - libgconf2-dev
      - libnss3
      - libasound2-dev
